source 'https://rubygems.org'
gem 'test-kitchen', '~> 1.17.0'
gem 'berkshelf'
group :integration do
  gem 'kitchen-azurerm', '~> 0.12.3'
end
group :integration do
  gem 'kitchen-inspec', '~> 0.19.0'
end
